import {
  createMockEnvelopeTransport,
  createOpenClawAdapter,
  sendEnvelopeWithHooks,
  type AgentRailContext,
  type X402BindingHook
} from "../src/index.js";

const adapter = createOpenClawAdapter();

const baseContext: AgentRailContext = {
  traceId: "trace_transport_001",
  requestId: "x402_transport_001",
  taskId: "task_transport_001",
  fromAgentId: "router-agent",
  toAgentId: "openclaw-agent",
  channel: "api",
  hopIndex: 1,
  conversationId: "conversation_transport_001",
  messageId: "message_transport_001",
  createdAt: new Date().toISOString()
};

const outboundEnvelope = adapter.toTaskEnvelope(
  {
    capability: "market-risk-eval",
    input: { symbol: "BTCUSD" }
  },
  baseContext
);

const transport = createMockEnvelopeTransport({
  handler: async (request) => {
    const resultEnvelope = adapter.toTaskResult(
      {
        summary: "Risk score generated by OpenClaw runtime.",
        data: { riskScore: 0.34 }
      },
      {
        ...baseContext,
        fromAgentId: "openclaw-agent",
        toAgentId: "router-agent",
        hopIndex: 2,
        messageId: "message_transport_002"
      }
    );

    return {
      endpoint: request.endpoint,
      status: 200,
      resultEnvelope
    };
  }
});

const x402Hooks: X402BindingHook[] = [
  {
    afterReceive: ({ request }) => ({
      payment: {
        mode: "x402",
        requestId: request.envelope.requestId,
        txHash: "0xfeedbeef",
        block: 20260001,
        status: "success",
        explorer: "https://testnet.kitescan.ai/tx/0xfeedbeef",
        verifiedAt: new Date().toISOString()
      },
      receiptRef: {
        requestId: request.envelope.requestId,
        txHash: "0xfeedbeef",
        block: 20260001,
        status: "success",
        endpoint: "/api/receipt/x402_transport_001"
      }
    })
  }
];

const delivery = await sendEnvelopeWithHooks(transport, {
  endpoint: "https://provider-agent.local/agentrail",
  envelope: outboundEnvelope,
  hooks: x402Hooks
});

console.log(JSON.stringify(delivery, null, 2));
